// export default {
//     CREATE_COMMENT_REQUEST: 'CREATE_COMMENT_REQUEST',
//     CREATE_COMMENT_FAILURE: 'CREATE_COMMENT_FAILURE',
//     CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
//     CREATE_COMMENT_DUPLICATE: 'CREATE_COMMENT_DUPLICATE',
//     GET_COMMENTS: 'GET_COMMENTS',
//     GET_COMMENTS_REQUEST: 'GET_COMMENTS_REQUEST',
//     GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
//     GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',
//     DESTROY_COMMENT: 'DESTROY_COMMENT'
// };

// export default () => {
//     const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST';
//     const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE';
//     const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
//     const CREATE_COMMENT_DUPLICATE = 'CREATE_COMMENT_DUPLICATE';
//     const GET_COMMENTS = 'GET_COMMENTS';
//     const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
//     const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
//     const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';
//     const DESTROY_COMMENT = 'DESTROY_COMMENT';
// }
