// export default {
//     CREATE_PROJECT_REQUEST: 'CREATE_PROJECT_REQUEST',
//     CREATE_PROJECT_FAILURE: 'CREATE_PROJECT_FAILURE',
//     CREATE_PROJECT_SUCCESS: 'CREATE_PROJECT_SUCCESS',
//     CREATE_PROJECT_DUPLICATE: 'CREATE_PROJECT_DUPLICATE',
//     GET_PROJECTS: 'GET_PROJECTS',
//     GET_PROJECTS_REQUEST: 'GET_PROJECTS_REQUEST',
//     GET_PROJECTS_SUCCESS: 'GET_PROJECTS_SUCCESS',
//     GET_PROJECTS_FAILURE: 'GET_PROJECTS_FAILURE',
//     DESTROY_PROJECT: 'DESTROY_PROJECT'
// };
