// export default {
//     CREATE_TOPIC_REQUEST: 'CREATE_TOPIC_REQUEST',
//     CREATE_TOPIC_FAILURE: 'CREATE_TOPIC_FAILURE',
//     CREATE_TOPIC_SUCCESS: 'CREATE_TOPIC_SUCCESS',
//     CREATE_TOPIC_DUPLICATE: 'CREATE_TOPIC_DUPLICATE',
//     GET_TOPICS: 'GET_TOPICS',
//     GET_TOPICS_REQUEST: 'GET_TOPICS_REQUEST',
//     GET_TOPICS_SUCCESS: 'GET_TOPICS_SUCCESS',
//     GET_TOPICS_FAILURE: 'GET_TOPICS_FAILURE',
//     INCREMENT_COUNT: 'INCREMENT_COUNT',
//     DECREMENT_COUNT: 'DECREMENT_COUNT',
//     DESTROY_TOPIC: 'DESTROY_TOPIC'
// };
