// export default {
//     TOGGLE_LOGIN_MODE: 'TOGGLE_LOGIN_MODE',
//     MANUAL_LOGIN_USER: 'MANUAL_LOGIN_USER',
//     LOGIN_SUCCESS_USER: 'LOGIN_SUCCESS_USER',
//     LOGIN_ERROR_USER: 'LOGIN_ERROR_USER',
//     SIGNUP_USER: 'SIGNUP_USER',
//     SIGNUP_SUCCESS_USER: 'SIGNUP_SUCCESS_USER',
//     SIGNUP_ERROR_USER: 'SIGNUP_ERROR_USER',
//     LOGOUT_USER: 'LOGOUT_USER',
//     LOGOUT_SUCCESS_USER: 'LOGOUT_SUCCESS_USER',
//     LOGOUT_ERROR_USER: 'LOGOUT_ERROR_USER'
// };
